name: Publish Python Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11.2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build the package
      run: python setup.py sdist bdist_wheel

#    - name: Publish to PyPI
#      env:
#        TWINE_USERNAME: __token__  # This tells twine to use the API token for authentication
#        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
#      run: twine upload dist/*
